/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./../theme/views/Article.vue')['default']
    Collection: typeof import('./../theme/views/Collection.vue')['default']
    Empty: typeof import('./../theme/views/Empty.vue')['default']
    Favorites: typeof import('./../theme/views/Favorites.vue')['default']
    RBackground: typeof import('./../theme/components/RBackground.vue')['default']
    RBreadcrumbs: typeof import('./../theme/components/RBreadcrumbs.vue')['default']
    RCard: typeof import('./../theme/components/RCard.vue')['default']
    RDescription: typeof import('./../theme/components/RDescription.vue')['default']
    REmpty: typeof import('./../theme/components/REmpty.vue')['default']
    Resource: typeof import('./../theme/views/Resource.vue')['default']
    RFavorite: typeof import('./../theme/components/RFavorite.vue')['default']
    RGiscus: typeof import('./../theme/components/RGiscus.vue')['default']
    RIcon: typeof import('./../theme/components/RIcon.vue')['default']
    RLayout: typeof import('./../theme/components/RLayout.vue')['default']
    RLinks: typeof import('./../theme/components/RLinks.vue')['default']
    RLogo: typeof import('./../theme/components/RLogo.vue')['default']
    RRelatedView: typeof import('./../theme/components/RRelatedView.vue')['default']
    RTags: typeof import('./../theme/components/RTags.vue')['default']
    RTitle: typeof import('./../theme/components/RTitle.vue')['default']
    RViewCard: typeof import('./../theme/components/RViewCard.vue')['default']
    RViewCards: typeof import('./../theme/components/RViewCards.vue')['default']
    Tags: typeof import('./../theme/views/Tags.vue')['default']
    VPFooter: typeof import('./../theme/components/overwrite/VPFooter.vue')['default']
    VPNavBarMenu: typeof import('./../theme/components/overwrite/VPNavBarMenu.vue')['default']
    VPNavScreenMenu: typeof import('./../theme/components/overwrite/VPNavScreenMenu.vue')['default']
  }
}
